package com.callibrity.vthreads.olympics.value;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public enum Country {
    AFG("AFG", "Afghanistan"),
    ALB("ALB", "Albania"),
    ALG("ALG", "Algeria"),
    AND("AND", "Andorra"),
    ANG("ANG", "Angola"),
    ANT("ANT", "Antigua and Barbuda"),
    ARG("ARG", "Argentina"),
    ARM("ARM", "Armenia"),
    AUS("AUS", "Australia"),
    AUT("AUT", "Austria"),
    AZE("AZE", "Azerbaijan"),
    BAH("BAH", "Bahamas"),
    BRN("BRN", "Bahrain"),
    BAN("BAN", "Bangladesh"),
    BAR("BAR", "Barbados"),
    BLR("BLR", "Belarus"),
    BEL("BEL", "Belgium"),
    BLZ("BLZ", "Belize"),
    BEN("BEN", "Benin"),
    BER("BER", "Bermuda"),
    BHU("BHU", "Bhutan"),
    BOL("BOL", "Bolivia"),
    BIH("BIH", "Bosnia and Herzegovina"),
    BOT("BOT", "Botswana"),
    BRA("BRA", "Brazil"),
    BRU("BRU", "Brunei"),
    BUL("BUL", "Bulgaria"),
    BUR("BUR", "Burkina Faso"),
    BDI("BDI", "Burundi"),
    KHM("KHM", "Cambodia"),
    CMR("CMR", "Cameroon"),
    CAN("CAN", "Canada"),
    CPV("CPV", "Cape Verde"),
    CAF("CAF", "Central African Republic"),
    CHAD("CHAD", "Chad"),
    CHI("CHI", "Chile"),
    CHN("CHN", "China"),
    COL("COL", "Colombia"),
    COM("COM", "Comoros"),
    COD("COD", "Congo, Democratic Republic of the"),
    COG("COG", "Congo, Republic of the"),
    CRC("CRC", "Costa Rica"),
    CIV("CIV", "Côte d'Ivoire"),
    CRO("CRO", "Croatia"),
    CUB("CUB", "Cuba"),
    CYP("CYP", "Cyprus"),
    CZE("CZE", "Czech Republic"),
    DEN("DEN", "Denmark"),
    DJI("DJI", "Djibouti"),
    DMA("DMA", "Dominica"),
    DOM("DOM", "Dominican Republic"),
    ECU("ECU", "Ecuador"),
    EGY("EGY", "Egypt"),
    ESA("ESA", "El Salvador"),
    GNQ("GNQ", "Equatorial Guinea"),
    ERI("ERI", "Eritrea"),
    EST("EST", "Estonia"),
    SWZ("SWZ", "Eswatini"),
    ETH("ETH", "Ethiopia"),
    FIJ("FIJ", "Fiji"),
    FIN("FIN", "Finland"),
    FRA("FRA", "France"),
    GAB("GAB", "Gabon"),
    GAM("GAM", "Gambia"),
    GEO("GEO", "Georgia"),
    GER("GER", "Germany"),
    GHA("GHA", "Ghana"),
    GRE("GRE", "Greece"),
    GRN("GRN", "Grenada"),
    GUM("GUM", "Guam"),
    GUA("GUA", "Guatemala"),
    GUI("GUI", "Guinea"),
    GBS("GBS", "Guinea-Bissau"),
    GUY("GUY", "Guyana"),
    HAI("HAI", "Haiti"),
    HON("HON", "Honduras"),
    HKG("HKG", "Hong Kong"),
    HUN("HUN", "Hungary"),
    ISL("ISL", "Iceland"),
    IND("IND", "India"),
    INA("INA", "Indonesia"),
    IRI("IRI", "Iran"),
    IRQ("IRQ", "Iraq"),
    IRL("IRL", "Ireland"),
    ISR("ISR", "Israel"),
    ITA("ITA", "Italy"),
    JAM("JAM", "Jamaica"),
    JPN("JPN", "Japan"),
    JOR("JOR", "Jordan"),
    KAZ("KAZ", "Kazakhstan"),
    KEN("KEN", "Kenya"),
    KIR("KIR", "Kiribati"),
    PRK("PRK", "Korea, North"),
    KOR("KOR", "Korea, South"),
    KOS("KOS", "Kosovo"),
    KUW("KUW", "Kuwait"),
    KGZ("KGZ", "Kyrgyzstan"),
    LAO("LAO", "Laos"),
    LAT("LAT", "Latvia"),
    LBN("LBN", "Lebanon"),
    LES("LES", "Lesotho"),
    LBR("LBR", "Liberia"),
    LBY("LBY", "Libya"),
    LIE("LIE", "Liechtenstein"),
    LTU("LTU", "Lithuania"),
    LUX("LUX", "Luxembourg"),
    MAD("MAD", "Madagascar"),
    MAW("MAW", "Malawi"),
    MAS("MAS", "Malaysia"),
    MDV("MDV", "Maldives"),
    MLI("MLI", "Mali"),
    MLT("MLT", "Malta"),
    MTN("MTN", "Mauritania"),
    MRI("MRI", "Mauritius"),
    MEX("MEX", "Mexico"),
    MDA("MDA", "Moldova"),
    MON("MON", "Monaco"),
    MGL("MGL", "Mongolia"),
    MNE("MNE", "Montenegro"),
    MAR("MAR", "Morocco"),
    MOZ("MOZ", "Mozambique"),
    MYA("MYA", "Myanmar"),
    NAM("NAM", "Namibia"),
    NRU("NRU", "Nauru"),
    NEP("NEP", "Nepal"),
    NED("NED", "Netherlands"),
    NZL("NZL", "New Zealand"),
    NCA("NCA", "Nicaragua"),
    NIG("NIG", "Niger"),
    NGR("NGR", "Nigeria"),
    MKD("MKD", "North Macedonia"),
    NOR("NOR", "Norway"),
    OMA("OMA", "Oman"),
    PAK("PAK", "Pakistan"),
    PLW("PLW", "Palau"),
    PLE("PLE", "Palestine"),
    PAN("PAN", "Panama"),
    PNG("PNG", "Papua New Guinea"),
    PAR("PAR", "Paraguay"),
    PER("PER", "Peru"),
    PHI("PHI", "Philippines"),
    POL("POL", "Poland"),
    POR("POR", "Portugal"),
    PUR("PUR", "Puerto Rico"),
    QAT("QAT", "Qatar"),
    ROU("ROU", "Romania"),
    RUS("RUS", "Russia"),
    RWA("RWA", "Rwanda"),
    SKN("SKN", "Saint Kitts and Nevis"),
    LCA("LCA", "Saint Lucia"),
    VIN("VIN", "Saint Vincent and the Grenadines"),
    SAM("SAM", "Samoa"),
    SMR("SMR", "San Marino"),
    STP("STP", "São Tomé and Príncipe"),
    KSA("KSA", "Saudi Arabia"),
    SEN("SEN", "Senegal"),
    SRB("SRB", "Serbia"),
    SEY("SEY", "Seychelles"),
    SLE("SLE", "Sierra Leone"),
    SIN("SIN", "Singapore"),
    SVK("SVK", "Slovakia"),
    SLO("SLO", "Slovenia"),
    SOL("SOL", "Solomon Islands"),
    SOM("SOM", "Somalia"),
    RSA("RSA", "South Africa"),
    SSD("SSD", "South Sudan"),
    ESP("ESP", "Spain"),
    SRI("SRI", "Sri Lanka"),
    SUD("SUD", "Sudan"),
    SUR("SUR", "Suriname"),
    SWE("SWE", "Sweden"),
    SUI("SUI", "Switzerland"),
    SYR("SYR", "Syria"),
    TPE("TPE", "Taiwan"),
    TJK("TJK", "Tajikistan"),
    TAN("TAN", "Tanzania"),
    THA("THA", "Thailand"),
    TLS("TLS", "Timor-Leste"),
    TOG("TOG", "Togo"),
    TGA("TGA", "Tonga"),
    TTO("TTO", "Trinidad and Tobago"),
    TUN("TUN", "Tunisia"),
    TUR("TUR", "Turkey"),
    TKM("TKM", "Turkmenistan"),
    TUV("TUV", "Tuvalu"),
    UGA("UGA", "Uganda"),
    UKR("UKR", "Ukraine"),
    UAE("UAE", "United Arab Emirates"),
    GBR("GBR", "United Kingdom"),
    USA("USA", "United States"),
    URU("URU", "Uruguay"),
    UZB("UZB", "Uzbekistan"),
    VAN("VAN", "Vanuatu"),
    VEN("VEN", "Venezuela"),
    VIE("VIE", "Vietnam"),
    ISV("ISV", "Virgin Islands"),
    YEM("YEM", "Yemen"),
    ZAM("ZAM", "Zambia"),
    ZIM("ZIM", "Zimbabwe");

    private final String code;
    private final String name;

    Country(String code, String name) {
        this.code = code;
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public String getName() {
        return name;
    }

    public static List<Country> randomCountries(int n) {
        final List<Country> countries = Arrays.asList(Country.values());
        Collections.shuffle(countries);
        return countries.subList(0, n);
    }

}
